export const Proformae = [
  {
    id: 1,
    customerName: "Ministry of Education",
    customerId: 13,
    email: "info@min.com",
    address: "Kampala",
    contactPerson: "Mugemusa",
  },
  {
    id: 2,
    customerName: "Ministry of Education",
    customerId: 13,
    email: "info@min.com",
    address: "Kampala",
    contactPerson: "Mugemusa",
  },
  {
    id: 3,
    customerName: "Ministry of Education",
    customerId: 13,
    email: "info@min.com",
    address: "Kampala",
    contactPerson: "Mugemusa",
  },
  {
    id: 4,
    customerName: "Ministry of Education",
    customerId: 13,
    email: "info@min.com",
    address: "Kampala",
    contactPerson: "Mugemusa",
  },
  {
    id: 5,
    customerName: "Ministry of Education",
    customerId: 13,
    email: "info@min.com",
    address: "Kampala",
    contactPerson: "Mugemusa",
  },
  {
    id: 6,
    customerName: "Ministry of Education",
    customerId: 13,
    email: "info@min.com",
    address: "Kampala",
    contactPerson: "Mugemusa",
  },
  {
    id: 7,
    customerName: "Ministry of Education",
    customerId: 13,
    email: "info@min.com",
    address: "Kampala",
    contactPerson: "Mugemusa",
  },
  {
    id: 8,
    customerName: "Ministry of Education",
    customerId: 13,
    email: "info@min.com",
    address: "Kampala",
    contactPerson: "Mugemusa",
  },
  {
    id: 9,
    customerName: "Ministry of Education",
    customerId: 13,
    email: "info@min.com",
    address: "Kampala",
    contactPerson: "Mugemusa",
  },
  {
    id: 10,
    customerName: "Ministry of Education",
    customerId: 13,
    email: "info@min.com",
    address: "Kampala",
    contactPerson: "Mugemusa",
  },
  {
    id: 11,
    customerName: "Ministry of Education",
    customerId: 13,
    email: "info@min.com",
    address: "Kampala",
    contactPerson: "Mugemusa",
  },
  {
    id: 12,
    customerName: "Ministry of Education",
    customerId: 13,
    email: "info@min.com",
    address: "Kampala",
    contactPerson: "Mugemusa",
  },
  {
    id: 13,
    customerName: "Ministry of Education",
    customerId: 13,
    email: "info@min.com",
    address: "Kampala",
    contactPerson: "Mugemusa",
  },
  {
    id: 14,
    customerName: "Ministry of Education",
    customerId: 13,
    email: "info@min.com",
    address: "Kampala",
    contactPerson: "Mugemusa",
  },
  {
    id: 15,
    customerName: "Ministry of Education",
    customerId: 13,
    email: "info@min.com",
    address: "Kampala",
    contactPerson: "Mugemusa",
  },
];
